/**
 * Companion State Definitions & Configurations for CodeBloom C++ Trainer.
 * Defines state constants, priority hierarchies, categories, and durations.
 */

export const COMPANION_STATES = {
  // Base Contextual States
  IDLE: 'IDLE',
  THINKING: 'THINKING',
  CODING: 'CODING',
  ULTIMATE_MASTERY: 'ULTIMATE_MASTERY',

  // Temporary Reaction States
  TEST_PASSED: 'TEST_PASSED',
  WRONG_OUTPUT: 'WRONG_OUTPUT',
  COMPILE_ERROR: 'COMPILE_ERROR',
  RUNTIME_ERROR: 'RUNTIME_ERROR',
  TIRED: 'TIRED',
  CELEBRATION: 'CELEBRATION',
  INDEPENDENT_SUCCESS: 'INDEPENDENT_SUCCESS',
  MASTERY: 'MASTERY'
};

export const STATE_CATEGORIES = {
  BASE: 'BASE',
  TEMPORARY: 'TEMPORARY'
};

export const STATE_CATEGORY_MAP = {
  [COMPANION_STATES.IDLE]: STATE_CATEGORIES.BASE,
  [COMPANION_STATES.THINKING]: STATE_CATEGORIES.BASE,
  [COMPANION_STATES.CODING]: STATE_CATEGORIES.BASE,
  [COMPANION_STATES.ULTIMATE_MASTERY]: STATE_CATEGORIES.BASE,

  [COMPANION_STATES.TEST_PASSED]: STATE_CATEGORIES.TEMPORARY,
  [COMPANION_STATES.WRONG_OUTPUT]: STATE_CATEGORIES.TEMPORARY,
  [COMPANION_STATES.COMPILE_ERROR]: STATE_CATEGORIES.TEMPORARY,
  [COMPANION_STATES.RUNTIME_ERROR]: STATE_CATEGORIES.TEMPORARY,
  [COMPANION_STATES.TIRED]: STATE_CATEGORIES.TEMPORARY,
  [COMPANION_STATES.CELEBRATION]: STATE_CATEGORIES.TEMPORARY,
  [COMPANION_STATES.INDEPENDENT_SUCCESS]: STATE_CATEGORIES.TEMPORARY,
  [COMPANION_STATES.MASTERY]: STATE_CATEGORIES.TEMPORARY
};

export const STATE_PRIORITIES = {
  [COMPANION_STATES.ULTIMATE_MASTERY]: 100,
  [COMPANION_STATES.MASTERY]: 90,
  [COMPANION_STATES.INDEPENDENT_SUCCESS]: 85,
  [COMPANION_STATES.CELEBRATION]: 80,
  [COMPANION_STATES.TIRED]: 70,
  [COMPANION_STATES.COMPILE_ERROR]: 60,
  [COMPANION_STATES.RUNTIME_ERROR]: 60,
  [COMPANION_STATES.WRONG_OUTPUT]: 50,
  [COMPANION_STATES.TEST_PASSED]: 40,
  [COMPANION_STATES.CODING]: 20,
  [COMPANION_STATES.THINKING]: 15,
  [COMPANION_STATES.IDLE]: 10
};

export const DEFAULT_STATE_DURATIONS_MS = {
  [COMPANION_STATES.TEST_PASSED]: 2000,
  [COMPANION_STATES.WRONG_OUTPUT]: 3000,
  [COMPANION_STATES.COMPILE_ERROR]: 3500,
  [COMPANION_STATES.RUNTIME_ERROR]: 3500,
  [COMPANION_STATES.TIRED]: 4000,
  [COMPANION_STATES.CELEBRATION]: 4000,
  [COMPANION_STATES.INDEPENDENT_SUCCESS]: 4500,
  [COMPANION_STATES.MASTERY]: 5000,
  [COMPANION_STATES.ULTIMATE_MASTERY]: 6000
};

export const TYPING_DEBOUNCE_MS = 1500;
export const REPEATED_FAILURE_THRESHOLD = 3;

// Phase D4B Contextual Reaction Tiers
export const ACHIEVEMENT_REACTION_TIERS = {
  FINAL: 'FINAL',
  MAJOR: 'MAJOR',
  IMPORTANT: 'IMPORTANT',
  MINOR: 'MINOR'
};

export const PROGRESSION_TIERS = {
  NOVICE: 'novice',
  APPRENTICE: 'apprentice',
  ARCHITECT: 'architect',
  PRACTITIONER: 'practitioner',
  MASTER: 'master'
};

/**
 * Maps numeric level (1-10) to visual progression tier.
 * @param {number} level
 * @returns {string} tier name ('novice' | 'apprentice' | 'architect' | 'practitioner' | 'master')
 */
export function getProgressionTier(level = 1) {
  const lvl = Number(level) || 1;
  if (lvl >= 9) return PROGRESSION_TIERS.MASTER;
  if (lvl >= 7) return PROGRESSION_TIERS.PRACTITIONER;
  if (lvl >= 5) return PROGRESSION_TIERS.ARCHITECT;
  if (lvl >= 3) return PROGRESSION_TIERS.APPRENTICE;
  return PROGRESSION_TIERS.NOVICE;
}
