import { lessons, modules, mastery } from './courseData.js';
import { assessCppSource, nextDifficulty, scrollToLearningWorkspace, updateLearnerProfile } from './learningEngine.js';

const app = document.querySelector('#app');
const stored = JSON.parse(localStorage.getItem('codebloom-profile') || '{"completed":[],"topics":{}}');
const state = { profile: stored, lessonId: 'cpp-basics', mode: 'course', source: lessons[0].example, feedback: null, showHint: false, exercise: 'mini', jumpToWorkspace: false };
const current = () => lessons.find(l => l.id === state.lessonId);
const save = () => localStorage.setItem('codebloom-profile', JSON.stringify(state.profile));
const esc = value => value.replace(/[&<>]/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]));

const sidebar = () => `<aside><div class="brand"><span>✦</span> CodeBloom <b>C++</b></div><button class="nav active" data-action="mode" data-mode="course">▦ &nbsp; Learning path</button><button class="nav" data-action="mode" data-mode="practice">⌁ &nbsp; Practice lab</button><button class="nav" data-action="mode" data-mode="challenge">⚡ &nbsp; Challenge mode</button><button class="nav" data-action="mode" data-mode="mastery">🏆 &nbsp; Mastery test</button><div class="divider"></div><p class="overline">YOUR JOURNEY</p><div class="progress-ring"><strong>${state.profile.completed.length}</strong><span>/ 20 lessons</span></div><p class="tiny">Every line you write is progress.</p></aside>`;

const map = () => `<section class="map"><div class="eyebrow">YOUR LEARNING PATH</div><h1>Write C++. <em>Don’t just read it.</em></h1><p class="lead">Short lessons, real typing, instant learning checks. Build the habit of turning questions into working programs.</p><div class="module-grid">${modules.map((m, i) => `<article class="module ${m.color}"><span>MODULE 0${i + 1} · LESSONS ${m.range}</span><h3>${m.name}</h3><p>${lessons.filter(l => l.module === m.name).map(l => l.title).join(' · ')}</p><button data-action="pick-module" data-module="${m.name}">Start module →</button></article>`).join('')}</div></section>`;

const lessonList = () => `<section class="lesson-list"><div class="list-top"><span class="eyebrow">LESSONS</span><span>${state.profile.completed.length}/20 complete</span></div>${lessons.map((l, i) => `<button class="lesson-item ${l.id === state.lessonId ? 'selected' : ''}" data-action="lesson" data-id="${l.id}"><span class="number">${String(i + 1).padStart(2,'0')}</span><span>${l.title}<small>${state.profile.completed.includes(l.id) ? 'Complete · ready to revisit' : l.module}</small></span>${state.profile.completed.includes(l.id) ? '<i>✓</i>' : ''}</button>`).join('')}</section>`;

const workspace = () => { const l = current(); const topic = state.profile.topics[l.id] || {}; const difficulty = nextDifficulty(topic); const prompt = state.exercise === 'mini' ? l.mini : state.exercise === 'medium' ? l.medium : l.hard; return `<main class="workspace"><div class="crumb">${l.module} <span>/</span> Lesson ${lessons.indexOf(l) + 1}</div><h2>${l.title}</h2><div class="lesson-body"><section class="teach"><div class="mission"><span>YOUR MISSION</span><strong>${l.mission}</strong></div><h3>In plain language</h3><p>${l.explanation}</p><div class="line-card"><b>How to read the example</b><ol><li><code>#include &lt;iostream&gt;</code> brings in screen input and output tools.</li><li><code>main()</code> is where every complete program begins.</li><li><code>cout</code> prints the value after it.</li><li><code>return 0;</code> says the program finished successfully.</li></ol></div><div class="adaptive ${difficulty}"><b>${difficulty === 'support' ? 'Let’s make this smaller' : difficulty === 'medium' ? 'You’re ready to stretch' : 'Start small, then grow'}</b><span>${difficulty === 'support' ? 'You have had a few tough attempts. Use the mini task and hint first.' : difficulty === 'medium' ? 'You have been solving confidently. Try a medium task next.' : 'Finish the mini task, then level up.'}</span></div></section><section class="code-zone"><div class="editor-top"><span><i></i> main.cpp</span><button data-action="reset">Reset example</button></div><textarea spellcheck="false" data-source>${esc(state.source)}</textarea><div class="editor-actions"><button class="hint" data-action="hint">${state.showHint ? 'Hint shown' : 'Need a hint?'}</button><button class="run" data-action="run">▷ Run learning check</button></div>${state.feedback ? `<div class="feedback ${state.feedback.status}"><b>${state.feedback.status === 'ready' ? '✓ Looking good' : '↳ One thing to fix'}</b><p>${state.feedback.message}</p></div>` : ''}</section></div><section class="exercise"><div><span class="eyebrow">TRY IT YOURSELF</span><h3>${state.exercise === 'mini' ? 'Tiny win' : state.exercise === 'medium' ? 'Build it up' : 'Independent build'}</h3><p>${prompt}</p>${state.showHint ? `<p class="hint-text">Hint: Start with the supplied program structure. Identify the values you need, then add one small step at a time.</p>` : ''}</div><div class="levels"><button class="${state.exercise === 'mini' ? 'selected' : ''}" data-action="exercise" data-level="mini">Easy</button><button class="${state.exercise === 'medium' ? 'selected' : ''}" data-action="exercise" data-level="medium">Medium</button><button class="${state.exercise === 'hard' ? 'selected' : ''}" data-action="exercise" data-level="hard">Hard</button></div></section></main>`; };

const independent = (type) => { const pool = type === 'mastery' ? mastery : lessons.map(l => l.hard); const question = pool[Math.floor(Math.random() * pool.length)]; return `<main class="independent"><div class="eyebrow">${type === 'mastery' ? 'C++ PROGRAMMING MASTERY TEST' : type === 'challenge' ? 'CHALLENGE MODE' : 'PRACTICE LAB'}</div><h1>${type === 'mastery' ? 'No hints. Just your craft.' : type === 'challenge' ? 'Solve it from the question.' : 'A fresh question is waiting.'}</h1><article class="problem"><span>PROGRAMMING QUESTION</span><h3>${question}</h3><p>${type === 'mastery' ? 'Plan the classes and functions you need. Then write, debug, and refine a complete program independently.' : 'Use the editor to create a complete C++ program. Run a learning check when you are ready.'}</p></article><div class="independent-editor"><div class="editor-top"><span><i></i> solution.cpp</span><button data-action="new-question">New question ↻</button></div><textarea data-source spellcheck="false">${esc(state.source)}</textarea><div class="editor-actions"><button class="hint" data-action="hint">${type === 'mastery' ? 'No hints in mastery' : 'Need a hint?'}</button><button class="run" data-action="run">▷ Run learning check</button></div>${state.feedback ? `<div class="feedback ${state.feedback.status}"><b>${state.feedback.status === 'ready' ? '✓ Looking good' : '↳ One thing to fix'}</b><p>${state.feedback.message}</p></div>` : ''}</div></main>`; };

const render = () => { app.innerHTML = `<div class="shell">${sidebar()}<div class="content"><header><div>${state.mode === 'course' ? 'Good to see you, coder.' : state.mode === 'mastery' ? 'Final assessment' : 'Keep your hands on the keyboard.'}</div><div class="header-right"><span>🔥 ${state.profile.completed.length * 3} XP</span><span class="avatar">R</span></div></header>${state.mode === 'course' ? `<div class="course">${map()}${lessonList()}${workspace()}</div>` : independent(state.mode)}</div></div>`; if (state.jumpToWorkspace) { state.jumpToWorkspace = false; scrollToLearningWorkspace(app); } };

app.addEventListener('input', e => { if (e.target.matches('[data-source]')) state.source = e.target.value; });
app.addEventListener('click', e => { const el = e.target.closest('[data-action]'); if (!el) return; const action = el.dataset.action;
  if (action === 'lesson') { state.lessonId = el.dataset.id; state.source = current().example; state.feedback = null; state.showHint = false; state.mode = 'course'; }
  if (action === 'pick-module') { state.lessonId = lessons.find(l => l.module === el.dataset.module).id; state.source = current().example; state.jumpToWorkspace = true; }
  if (action === 'mode') { state.mode = el.dataset.mode; state.feedback = null; }
  if (action === 'exercise') state.exercise = el.dataset.level;
  if (action === 'hint') state.showHint = true;
  if (action === 'reset') { state.source = current().example; state.feedback = null; }
  if (action === 'new-question') { state.source = current().example; state.feedback = null; }
  if (action === 'run') { state.feedback = assessCppSource(state.source); if (state.mode === 'course') { state.profile = updateLearnerProfile(state.profile, current().id, state.feedback.status === 'ready'); save(); } }
  render();
});
render();
